# Examples - Tues, Nov 5
## Section 2.B, "Continuing NumPy"

In [1]:
import numpy as np

2.B.1 Using loops with arrays

In [2]:
array1d = np.array([2, 4, 6, 8])
array1d

array([2, 4, 6, 8])

In [4]:
for i in array1d:
    print(i)

2
4
6
8


In [6]:
arr3d = np.array([[[8,7], [6, 5]], [[4, 3], [2, 1]]])

for i in arr3d:
    print(i)

[[8 7]
 [6 5]]
[[4 3]
 [2 1]]


In [7]:
for i in arr3d:
    for x in i:
        print(x)

[8 7]
[6 5]
[4 3]
[2 1]


In [8]:
for i in arr3d:
    for x in i:
        for a in x:
            print(a)

8
7
6
5
4
3
2
1


### 2.B.2 Joining arrays with `concatenate()`

In [9]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([11, 12, 13])

In [12]:
arr_c = np.concatenate((arr_a, arr_b))
arr_c

array([ 1,  2,  3, 11, 12, 13])

In [14]:
arr_d = np.concatenate((arr_a, arr_b), axis=0)
arr_d

array([ 1,  2,  3, 11, 12, 13])

In [16]:
arr_stacked = np.stack((arr_a, arr_b))
arr_stacked

array([[ 1,  2,  3],
       [11, 12, 13]])

In [18]:
arr_stacked2 = np.stack((arr_a, arr_b), axis=1)
arr_stacked2

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [19]:
stack_of_stacks = np.concatenate((arr_stacked, arr_stacked))
stack_of_stacks

array([[ 1,  2,  3],
       [11, 12, 13],
       [ 1,  2,  3],
       [11, 12, 13]])

In [20]:
stack_of_stacks2 = np.concatenate((arr_stacked, arr_stacked), axis=1)
stack_of_stacks2

array([[ 1,  2,  3,  1,  2,  3],
       [11, 12, 13, 11, 12, 13]])

In [28]:
ex_vstack = np.vstack((arr_stacked,arr_stacked))
ex_vstack

array([[ 1,  2,  3],
       [11, 12, 13],
       [ 1,  2,  3],
       [11, 12, 13]])

In [29]:
ex_hstack = np.hstack((arr_stacked,arr_stacked))
ex_hstack

array([[ 1,  2,  3,  1,  2,  3],
       [11, 12, 13, 11, 12, 13]])

In [30]:
ex_dstack = np.dstack((arr_stacked,arr_stacked))
ex_dstack

array([[[ 1,  1],
        [ 2,  2],
        [ 3,  3]],

       [[11, 11],
        [12, 12],
        [13, 13]]])

### 2.B.5 Splitting arrays

In [31]:
ex_vstack

array([[ 1,  2,  3],
       [11, 12, 13],
       [ 1,  2,  3],
       [11, 12, 13]])

In [33]:
split_3_ways = np.array_split(ex_vstack, 3)
split_3_ways

[array([[ 1,  2,  3],
        [11, 12, 13]]),
 array([[1, 2, 3]]),
 array([[11, 12, 13]])]

In [34]:
split_4_ways = np.array_split(ex_vstack, 4)
split_4_ways

[array([[1, 2, 3]]),
 array([[11, 12, 13]]),
 array([[1, 2, 3]]),
 array([[11, 12, 13]])]

In [35]:
split_4_0 = np.array_split(ex_vstack, 4, axis=0)
split_4_0

[array([[1, 2, 3]]),
 array([[11, 12, 13]]),
 array([[1, 2, 3]]),
 array([[11, 12, 13]])]

In [36]:
split_4_1 = np.array_split(ex_vstack, 4, axis=1)
split_4_1

[array([[ 1],
        [11],
        [ 1],
        [11]]),
 array([[ 2],
        [12],
        [ 2],
        [12]]),
 array([[ 3],
        [13],
        [ 3],
        [13]]),
 array([], shape=(4, 0), dtype=int32)]

In [ ]:
# helper functions: hsplit(), vsplit(), dsplit()

### 2.B.6 Using `where()` to search and alter arrays

In [37]:
values = np.array([4, 9, 4, 8, 0, 6])
cond1 = np.where(values < 5)
cond1

(array([0, 2, 4], dtype=int64),)

In [39]:
print(np.array(cond1))

[[0 2 4]]


In [40]:
print(cond1)

(array([0, 2, 4], dtype=int64),)


In [43]:
cond2 = np.where(values < 5, values, values * .9)
print(cond2)

[4.  8.1 4.  7.2 0.  5.4]


In [44]:
cond3 = np.where(values < 5, values, 'over 5')
print(cond3)

['4' 'over 5' '4' 'over 5' '0' 'over 5']


In [45]:
ex_vstack

array([[ 1,  2,  3],
       [11, 12, 13],
       [ 1,  2,  3],
       [11, 12, 13]])

In [49]:
cond4 = np.where(ex_vstack > 10)

In [50]:
cond5 = np.where(ex_vstack > 10, ex_vstack, 'down')
print(cond5)

[['down' 'down' 'down']
 ['11' '12' '13']
 ['down' 'down' 'down']
 ['11' '12' '13']]


### 2.B.7 Sorting arrays

In [52]:
values

array([4, 9, 4, 8, 0, 6])

In [53]:
ex_vstack

array([[ 1,  2,  3],
       [11, 12, 13],
       [ 1,  2,  3],
       [11, 12, 13]])

In [55]:
print(np.sort(values))

[0 4 4 6 8 9]


In [56]:
print(np.sort(ex_vstack))

[[ 1  2  3]
 [11 12 13]
 [ 1  2  3]
 [11 12 13]]


In [57]:
print(np.sort(cond5))

[['down' 'down' 'down']
 ['11' '12' '13']
 ['down' 'down' 'down']
 ['11' '12' '13']]


In [59]:
arr_a = np.array([7, 5, 3])
arr_b = np.array([11, 9, 7])
ab = np.hstack((arr_a, arr_b))
ab

array([ 7,  5,  3, 11,  9,  7])

In [60]:
ab2 = np.vstack((arr_a, arr_b))
ab2

array([[ 7,  5,  3],
       [11,  9,  7]])

In [61]:
ab3 = np.dstack((arr_a, arr_b))
ab3

array([[[ 7, 11],
        [ 5,  9],
        [ 3,  7]]])

In [63]:
print(np.sort(ab))

[ 3  5  7  7  9 11]


In [64]:
print(np.sort(ab2))

[[ 3  5  7]
 [ 7  9 11]]


In [65]:
print(np.sort(ab3))

[[[ 7 11]
  [ 5  9]
  [ 3  7]]]


### 2.B.8 Filtering arrays

In [66]:
z = np.array([14, 9, 4, 18, 0, 6])
z

array([14,  9,  4, 18,  0,  6])

In [69]:
# To create a boolean index using standard Python

filter_z = []

for i in z:
    if i > 10:
        filter_z.append(True)
    else:
        filter_z.append(False)

print(filter_z)

[True, False, False, True, False, False]


In [70]:
# applying boolean index

y = z[filter_z]
print(y)

[14 18]


In [71]:
z

array([14,  9,  4, 18,  0,  6])

In [76]:
x = z > 10
z_over_10 = z[x]
print(z_over_10)

[14 18]


# Section 2.C Random in NumPy

### 2.C.2 Simple random functions

In [79]:
# Array of random integers

h = np.random.randint(1, 200, size=(3, 4, 2))
h

array([[[ 99, 132],
        [183, 198],
        [117,  38],
        [146, 175]],

       [[172,  73],
        [  3, 107],
        [189, 148],
        [ 31,  38]],

       [[ 56, 133],
        [164, 156],
        [ 48, 156],
        [146,  34]]])

In [81]:
# Array of random floats (btwn 0 and 1)

j = np.random.rand(3, 4, 2)
j

array([[[0.70687479, 0.90375198],
        [0.83204558, 0.39698631],
        [0.3975653 , 0.54286576],
        [0.30184914, 0.54888286]],

       [[0.51280252, 0.32440754],
        [0.27891729, 0.81209146],
        [0.77040839, 0.24439282],
        [0.12043564, 0.46768528]],

       [[0.2901464 , 0.64331756],
        [0.18499671, 0.00750372],
        [0.96446861, 0.42797822],
        [0.48332216, 0.16874984]]])

In [82]:
z

array([14,  9,  4, 18,  0,  6])

In [83]:
h

array([[[ 99, 132],
        [183, 198],
        [117,  38],
        [146, 175]],

       [[172,  73],
        [  3, 107],
        [189, 148],
        [ 31,  38]],

       [[ 56, 133],
        [164, 156],
        [ 48, 156],
        [146,  34]]])

In [87]:
choice_z = np.random.choice(z, size=(3, 2))
choice_z

array([[ 9, 18],
       [ 6,  6],
       [ 9,  4]])

In [99]:
choice_h = np.random.choice(h[0][0], size=(5))
choice_h

array([132, 132,  99, 132, 132])

In [ ]:
choice_k = np.random.choice([3, 5, 7, 9, 11, 13], size=(3, 2))
choice_k

In [103]:
# Random distribution using probability density

choice_m = np.random.choice(['a', 'b', 7, 9, 11, 13], p=[.1, .1, .1, .1, .2, .4], size=(3, 2))
choice_m

array([['13', '13'],
       ['13', 'a'],
       ['13', '9']], dtype='<U11')

### 2.C.5 Normal distribution

In [108]:
x_normal = np.random.normal(loc=5, scale=2, size=(3, 2, 4))
x_normal

array([[[2.49637163, 4.96656732, 5.36684312, 2.94617679],
        [3.75212001, 6.56045433, 8.70221565, 4.51038339]],

       [[7.15334341, 4.30397128, 5.40504351, 2.29122928],
        [4.54563424, 9.08970657, 6.50959569, 5.01266795]],

       [[5.57064298, 5.48690982, 5.12149375, 4.18841432],
        [4.10895765, 4.43872934, 4.01500673, 4.29930754]]])